/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/payment-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Payment Intent */
        post: operations["create_payment_intent_v1_payment_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_v1_approvals__approval_request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approvals/{approval_request_id}/grant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Approval
         * @description Stands in for a human tapping 'approve' in a banking app. The returned
         *     token is bound to the exact amount, merchant, currency and cart the human
         *     was shown.
         */
        post: operations["grant_approval_v1_approvals__approval_request_id__grant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile
         * @description Resolve UNKNOWN payments by querying the provider. Never re-submits.
         */
        post: operations["reconcile_v1_reconcile_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Transactions */
        get: operations["list_transactions_v1_transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Events */
        get: operations["audit_events_v1_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit Verify */
        get: operations["audit_verify_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Audit Checkpoint
         * @description Force an anchor of the current chain head into the independent store.
         */
        post: operations["audit_checkpoint_v1_audit_checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorizationToken */
        AuthorizationToken: {
            /** Token */
            token: string;
            /** Payment Authorization Id */
            payment_authorization_id: string;
            /** Merchant Id */
            merchant_id: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Cart Hash */
            cart_hash: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Max Uses
             * @default 1
             * @constant
             */
            max_uses: 1;
            /** Policy Version */
            policy_version: string;
        };
        /** CartItem */
        CartItem: {
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number | string;
        };
        /**
         * Decision
         * @enum {string}
         */
        Decision: "ALLOW" | "REQUIRE_APPROVAL" | "BLOCK";
        /** DecisionResponse */
        DecisionResponse: {
            /** Payment Authorization Id */
            payment_authorization_id: string;
            decision: components["schemas"]["Decision"];
            /** Reason Codes */
            reason_codes: string[];
            state: components["schemas"]["PaymentState"];
            risk: components["schemas"]["RiskAssessment"];
            /** Policy Version */
            policy_version: string;
            authorization?: components["schemas"]["AuthorizationToken"] | null;
            /** Provider Reference */
            provider_reference?: string | null;
            /** Audit Event Id */
            audit_event_id?: string | null;
            /** Audit Hash */
            audit_hash?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Replayed
             * @default false
             */
            replayed: boolean;
            /**
             * Message
             * @default
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MerchantContent
         * @description Untrusted text harvested from the merchant surface. Never an instruction.
         */
        MerchantContent: {
            /** @default unknown */
            source_type: components["schemas"]["SourceType"];
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Text
             * @default
             */
            text: string;
        };
        /**
         * PaymentIntent
         * @description The typed payment instruction. This is the only thing that can move money.
         */
        PaymentIntent: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Agent Id */
            agent_id: string;
            /** User Id */
            user_id: string;
            /** Delegation Id */
            delegation_id: string;
            /** Merchant Id */
            merchant_id: string;
            /**
             * Merchant Verified
             * @default false
             */
            merchant_verified: boolean;
            /** Amount */
            amount: number | string;
            /** Currency */
            currency: string;
            /** Items */
            items: components["schemas"]["CartItem"][];
            /**
             * Purpose
             * @default
             */
            purpose: string;
            merchant_content?: components["schemas"]["MerchantContent"];
            /** Tool Arguments */
            tool_arguments?: Record<string, never>;
            /** Approval Token */
            approval_token?: string | null;
        };
        /**
         * PaymentState
         * @enum {string}
         */
        PaymentState: "CREATED" | "AUTHORIZED" | "SUBMITTED" | "CONFIRMED" | "FAILED" | "TIMEOUT" | "UNKNOWN" | "EXPIRED";
        /** RiskAssessment */
        RiskAssessment: {
            signals: components["schemas"]["RiskSignals"];
            /** Weighted Score */
            weighted_score: number;
            /** Policy Version Context */
            policy_version_context: string;
        };
        /**
         * RiskSignals
         * @description Evidence only. Contains no decision field, by design.
         */
        RiskSignals: {
            /**
             * Injection Confidence
             * @default 0
             */
            injection_confidence: number;
            /** Injection Labels */
            injection_labels?: string[];
            /**
             * Policy Violation Score
             * @default 0
             */
            policy_violation_score: number;
            /**
             * Budget Anomaly Score
             * @default 0
             */
            budget_anomaly_score: number;
            /**
             * Merchant Risk Score
             * @default 0
             */
            merchant_risk_score: number;
            /**
             * Velocity Risk Score
             * @default 0
             */
            velocity_risk_score: number;
            /**
             * Source Trust Score
             * @default 1
             */
            source_trust_score: number;
            /**
             * Classifier Degraded
             * @default false
             */
            classifier_degraded: boolean;
        };
        /**
         * SourceType
         * @description Where the content around this transaction came from. Drives trust score.
         * @enum {string}
         */
        SourceType: "official_api" | "verified_catalog" | "scraped_page" | "email" | "user_upload" | "unknown";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    create_payment_intent_v1_payment_intents_post: {
        parameters: {
            query?: {
                /** @description Submit to the payment provider when the decision is ALLOW. */
                execute?: boolean;
            };
            header?: {
                authorization?: string | null;
                "x-request-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentIntent"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_v1_approvals__approval_request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    grant_approval_v1_approvals__approval_request_id__grant_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconcile_v1_reconcile_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_transactions_v1_transactions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_events_v1_audit_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_verify_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    audit_checkpoint_v1_audit_checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
